server:
  port: 9080

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malyadri4java/spring-cloud-microservice
          #uri: file://C:\\workspace\\spring
          clone-on-start: true
