spring:
  application:
    name: user-service
server:
  port: 9101
  servlet:
    context-path: /user
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    #preferIpAddress: true
    hostname: localhost

## Configuring info endpoint
info:
  app:
    name: Spring Boot User Service Application
    description: This is my first spring boot application
    version: 1.0.0
